simulation_test: 
	cc -ggdb board.c simulator.c simulation_test.c -o tescik

AutomatKomorkowyLIFE:	
	cc board.c simulator.c main.c -o "AutomatKomorkowyLIFE"
       	
board_test:
	cc board.c board_test.c -o "board_test"
