automat: 
	cc  board.c simulator.c pngx.c main.c -o AutomatKomorkowyLIFE -lpng

simulation_test: 
	cc  board.c simulator.c simulation_test.c -o simulation_test

board_test:
	cc  board.c board_test.c -o "board_test"

png_test:
	cc  -ggdb png_test.c pngx.c board.c -o png_test -lpng

